### ISSUE TITLE
UTF-8 character support for label and metric names 

### ISSUE THREAD

**Issue by jesusvazquez** [prometheus/prometheus#12630]
### Problem

Relates to:
- [Original discussion](https://groups.google.com/g/prometheus-developers/c/-O23C4_9Ijc/m/Zrk2UOaNAQAJ) 
- Brainstorming doc [Quoting Prometheus Names](https://docs.google.com/document/d/1yFj5QSd1AgCYecZ9EJ8f2t4OgF2KBZgJYVde-uzVEtI/edit) 
- [OTEL Attribute compatibility section](https://docs.google.com/document/d/1epvoO_R7JhmHYsII-GJ6Yw99Ky91dKOqOtZGqX7Bk0g/edit#heading=h.yqsgk5wz7ww0) 

We are creating this issue as part of the OTEL Support milestone so it will be OTEL oriented but the problem is general to prometheus and has been around for a long time.

OTel allows UTF-8 in label names while Prometheus has a much [more restrictive set](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). This is causing friction for users when using Prometheus. In particular, . (dot) is a very common character in OTel and we convert that to _ when converting to Prometheus. For example, service.version becomes service_version. 

While this might look trivial, it causes friction because the traces and logs are likely stored in other databases which don’t have this restriction. Hence context switching between different datasources is not trivial.

### Design doc

In a previous dev summit the prometheus team [had consensus](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit#bookmark=id.nk7gkeipbviy) that at this stage a design doc is required to discuss about this topic.

**Comment by ywwg** [comment]
I am currently working on a design and prototype code for this change

**Comment by jesusvazquez** [comment]
Great @ywwg , just assigned this issue to you.

**Comment by ywwg** [comment]
proposal: https://github.com/prometheus/proposals/pull/28

**Comment by ywwg** [comment]
@jesusvazquez can you let me edit this bug so I can update the task list at the top?

```[tasklist]
### Tasks
- [ ] https://github.com/prometheus/common/issues/527
- [ ] https://github.com/prometheus/client_golang/issues/1369
- [ ] https://github.com/prometheus/prometheus/issues/12630
```

**Comment by gouthamve** [comment]
Hi, I am not sure how we can give you that access. Best thing would be to open a new issue with the new context and task list and we can close this as a duplicate.

**Comment by jesusvazquez** [comment]
Closing in favor of https://github.com/prometheus/prometheus/issues/13095
