### ISSUE TITLE
Epic: Implement UTF-8 character support for label and metric names

### ISSUE THREAD

**Issue by ywwg** [prometheus/prometheus#13095]
### Tracking Issue

Relates to:

[Original discussion](https://groups.google.com/g/prometheus-developers/c/-O23C4_9Ijc/m/Zrk2UOaNAQAJ)
Brainstorming doc [Quoting Prometheus Names](https://docs.google.com/document/d/1yFj5QSd1AgCYecZ9EJ8f2t4OgF2KBZgJYVde-uzVEtI/edit)
[OTEL Attribute compatibility section](https://docs.google.com/document/d/1epvoO_R7JhmHYsII-GJ6Yw99Ky91dKOqOtZGqX7Bk0g/edit#heading=h.yqsgk5wz7ww0)

We are creating this issue as part of the OTEL Support milestone so it will be OTEL oriented but the problem is general to prometheus and has been around for a long time.

OTel allows UTF-8 in label names while Prometheus has a much [more restrictive set](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). This is causing friction for users when using Prometheus. In particular, . (dot) is a very common character in OTel and we convert that to _ when converting to Prometheus. For example, service.version becomes service_version.

Proposals have been accepted to do this work:  

* https://github.com/prometheus/proposals/blob/main/proposals/2023-08-21-utf8.md
* ~https://github.com/prometheus/proposals/blob/main/proposals/2023-11-13-utf8-migration.md~  **Note**: the migration proposal has been deprioritized due to higher-than-anticipated complexity and lack of concrete demand.

### Minimum Viable Product ✅ 

MVP is defined as round-trip support for UTF-8 names and labels in the Go language with scraping and remote-write. This serves as an initial testing bed and implementation example for other language bindings.

- [x] prom/common: update openmetrics_parse, promparse (https://github.com/prometheus/common/pull/537)
- [x] prom/common: content negotiation in scraping (https://github.com/prometheus/common/pull/570)
- [x] prom/promtheus: content negotiation and flags (https://github.com/prometheus/prometheus/pull/14490)
- [x] prom/client_golang: (https://github.com/prometheus/client_golang/issues/1369)
- [x] prom/prometheus: Update some parsers (https://github.com/prometheus/prometheus/pull/13271)
- [x] prom/common: update text_parse (go version) (https://github.com/prometheus/common/issues/554)
- [x] [Go client library](https://github.com/prometheus/client_golang/issues/1369): no changes required
- [x] https://github.com/prometheus/prometheus/issues/14728
- [x] prom/prometheus: flip flag defaults in v3 branch (https://github.com/prometheus/prometheus/pull/14705)
- [x] prom/prometheus: flip flag defaults in main (https://github.com/prometheus/prometheus/issues/14674)

### Follow-ons

- [ ] https://github.com/prometheus/client_golang/pull/1641
- [x] #15202
- [ ] https://github.com/prometheus/prometheus/issues/15243
- [x] https://github.com/prometheus/prometheus/issues/15259
- [x] https://github.com/prometheus/prometheus/pull/15399
- [x] https://github.com/prometheus/common/issues/723
- [x] https://github.com/prometheus/prometheus/issues/15470
- [x] #15528
- [ ] #15791
- [x] https://github.com/prometheus/prometheus/issues/16027
- [ ] https://github.com/prometheus/prometheus/issues/16034
- [ ] https://github.com/prometheus/prometheus/issues/16093

### Write-side tasks
- [x] prom/pushgateway: (https://github.com/prometheus/pushgateway/issues/623)

### OTLP
- [x] UTF-8 support in Otel Prom SDK exporter  (https://github.com/open-telemetry/opentelemetry-go/pull/5755) 
- [x] https://github.com/prometheus/prometheus/pull/15258
- [ ] https://github.com/prometheus/prometheus/issues/14990
- [ ] https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35459

### Read-side tasks

Mixed-block reading is deprioritized due to the difficult and lack of proven need

- [ ] ~#13765~
- [x] ~prom/prometheus: tsdb meta.json bump~
- [x] ~prom/prometheus: tsdb multiquerying for otel and other migration cases~
- [x] prom/prometheus: content negotiation in querying?
- [x] prom/prometheus: update web/ui parser (https://github.com/prometheus/prometheus/issues/13564)

### Client Libraries
- [ ] https://github.com/prometheus/prometheus/issues/16092

### Grafana user-visible changes ✅

Not directly related to Prometheus, but this is the bug I'm using for all the related work, so...

- [x] Grafana Epic: https://github.com/grafana/grafana/issues/91253
- [x] grafana/grafana: https://github.com/grafana/grafana/issues/74875
- [ ] grafana/mimir: https://github.com/grafana/mimir/issues/10283

### Other task refs
- [x] https://github.com/prometheus/common/issues/527
- [x] [update prom3 migration guide](https://github.com/prometheus/prometheus/pull/15099)
- [x] identify other docs to update
- [ ] https://github.com/grafana/mimir/issues/9457

(This is a clone of https://github.com/prometheus/prometheus/issues/12630 that I own so I can edit the top-level comment and track work here)

**Comment by ywwg** [comment]
Design work will be needed for the tsdb changes -- determining how to query data that was written with old versions of prometheus will be tricky, for instance if an Otel metric goes from _ to . but doesn't use the U__ quoting syntax in the old metrics.

**Comment by spedersen-emailage** [comment]
Ran into this issue with Grafana alert labels vs. Prometheus alert labels. Grafana supports `-`, but Prometheus does not. In order to avoid conflicts or multiple label sets, we'll need to replace `-` with `_` in all of our alerts and notification policies next week.

Consistency between OTel, Prometheus, etc. would be fantastic.

**Comment by ywwg** [comment]
https://github.com/prometheus/common/pull/537 in progress

**Comment by ywwg** [comment]
https://github.com/ywwg/common/pull/2 in draft (write-side content negotiation)

**Comment by mhausenblas** [comment]
Thanks for this! Question concerning "User-visible changes:" section. Should we take into account CNCF projects such as Thanos and Cortex?

**Comment by jmichalek132** [comment]
Linking another utf8 support related issue https://github.com/prometheus/prometheus/issues/14990

**Comment by beorn7** [comment]
I think we need more UI updates:
- Autocompletion: If I just start to type a metric name, I get new-style names offered, but if I let them autocomplete, I end up with invalid syntax because it autocompletes to just `foo.bar` rather than doing its thing and autocompleting to `{"foo.bar"}`. If I try to be smart and start typing `{"`, then I get no autocompletion at all.
- In the table view, new-style metric names are displayed with invalid syntax, i.e. 
![image](https://github.com/user-attachments/assets/6752c33c-f74b-4a88-bb29-b3cc90173570)

The example above is still benign. The only annoying part is that you couldn't write it that way in PromQL.
However, how about this:
![image](https://github.com/user-attachments/assets/988a3ff6-b06d-48c0-9c1c-fc4653d6a57a)

(The metric name above is literally `foo{bar="baz"}`.)

**Comment by beorn7** [comment]
Hello from the bug scrub!

Still an ongoing truly epic journey. :)

**Comment by ywwg** [comment]
Although UTF-8 is not "finished", I believe the work has outgrown the usefulness of this bug.  I'm going to add UTF-8 labels to the relevant items and then close this bug.
