### ISSUE TITLE
[Meta Issue] Created Timestamp Plan 

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#14217]
### Proposal

This issue covers outstanding issues and explains the proposed longer term plan for Created Timestamp feature in Prometheus Ecosystem.

### Background

In 2023 we had amazing @ArthurSens as [our GSoC mentee to introduce Created Timestamp feature](https://github.com/prometheus/prometheus/issues/6541) (CT). We delivered initial piping in Prometheus proto format, client_golang and initial Prometheus feature called [`created-timestamp-zero-ingestion`](https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection). We also delivered a PromCon 2023 [talk](https://www.youtube.com/watch?v=nWf0BfQ5EEA) explaining Created Timestamp. Last, but no least, we gained super active and talented maintainer @ArthurSens 

However, this is only the beginning for full productionizing and adoption of Created Timestamp. As mentioned in [the CT proposal @ArthurSens did](https://github.com/prometheus/proposals/blob/main/proposals/2023-06-13_created-timestamp.md#:~:text=For%20those%20reasons%2C%20created%20timestamps%20will%20also%20be%20stored%20as%20metadata%20per%20series%2C%20following%20the%20similar%20logic%20used%20for%20the%20zero%2Dinjection.), the `zero injection` will be accompanied (or replaced) by metadata storage and there further various work items that are still missing. 

In 2024 summer we have @Maniktherana on another round of GSoC mentorship around CT feature 🤗 

### Issues

Following work is planned. A bit of rationales are provided for prioritization purposes:

* [X] PRW spec change: https://github.com/prometheus/prometheus/issues/13368
* [ ] Parse CT from OM Text: https://github.com/prometheus/prometheus/issues/12980
* [ ] Potentially remove those `_created` metrics once parsed (or always): https://github.com/prometheus/prometheus/issues/6541 
   * This also solves: https://github.com/prometheus/prometheus/issues/10164
* [ ] CT for histograms: https://github.com/prometheus/prometheus/issues/13384
* [ ] Propose alternative CT attachment to OM Text: https://github.com/prometheus/prometheus/issues/13537
   * This solves known drawbacks of `_created` series mechanism.
* [ ] Store CT in metadata storage (todo ticket)
  *  The this solves known drawbacks with `created-timestamp-zero-ingestion` feature. Potentially allow deprecating or at least reduce the use of zero ingestion feature.
  * [ ] Use CT from metadata storage in PromQL engine (todo ticket)
  * [ ] Use CT from metadata storage in Remote Write 2.0 (todo ticket)
* [ ] Add optional feature for auto-creation of CT (todo ticket)

**Comment by bboreham** [comment]
Hello from the bug-scrub!  Just checking, is this issue still up to date?
