### ISSUE TITLE
[meta] Remote Write 2.0 Spec Feedback List

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#14360]
### Proposal

This ticket coordinates open questions on further changes to 2.0 PRW spec while it's in an experimental stage. Best effort, we don't need to do all below to get to stable, but we could address/consider at least.

* [x] Response Confirmation https://github.com/prometheus/prometheus/issues/14359
* [x] Double check if any change would be useful for https://github.com/prometheus/proposals/pull/37 cc @aknuds1 
* [ ] Timestamp on exemplar is MUST @cstyan  
* [ ] Anything for UTF-8? @ywwg

**Comment by aknuds1** [comment]
Regarding _Add proposal: Simplify joins with info metrics in PromQL_, what we would need is annotation of info metrics and which are their _identifying labels_ (so this can be persisted upon ingestion). For reference, the OpenMetrics protobuf exposition format supports annotating info metrics' identifying labels.

**Comment by bwplotka** [comment]
cc @krajorama @cstyan we discussed MUST exemplar timestamp (from MAY) change in spec. I think if the rationales are good, we could consider that, it's a small change. Sender in the worst case could add exemplar timestamp. Discussion happens on Slack now: https://cloud-native.slack.com/archives/C06B8KJUU2Y/p1722445290276849

**Comment by bwplotka** [comment]
@aknuds1 as per https://github.com/prometheus/prometheus/issues/14360#issuecomment-2195822758

Ok, so indeed so it's indeed value of ... labels not float value: https://github.com/OpenObservability/OpenMetrics/blob/main/proto/openmetrics_data_model.proto#L186

I think that makes it "easy" in a sense, that anytime once info metric and info function matures, we can do PRW 2.1 and add another repeated field next to samples, histograms, but essentially "info samples". Or something else, but as an addition later on. Does it make sense?

cc @dashpole wonder how info metric would work on our side 🤔 in this form. For OTLP it looks like info metrics do not exists, there is only notion of "target info" non-indexed labels: https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L71

**Comment by aknuds1** [comment]
> I think that makes it "easy" in a sense, that anytime once info metric and info function matures, we can do PRW 2.1 and add another repeated field next to samples, histograms, but essentially "info samples". Or something else, but as an addition later on. Does it make sense?

@bwplotka If it can be added in a backwards compatible manner, that sounds great to me :)

**Comment by bwplotka** [comment]
Added @ywwg https://github.com/prometheus/prometheus/pull/14490/files#r1700444116 potential field that was proposed in their PR, if useful.

**Comment by ywwg** [comment]
I have an in-progress PR that deals with UTF8 content negotiation: https://github.com/prometheus/prometheus/pull/14490 -- yes, this includes a new name escaping term that enables the feature

**Comment by dashpole** [comment]
> cc @dashpole wonder how info metric would work on our side 🤔 in this form. For OTLP it looks like info metrics do not exists, there is only notion of "target info" non-indexed labels: https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L71

Currently we use `metric.metadata` to store `prometheus.type=info` to note that a gauge metric originated as a prometheus info-typed metric: https://github.com/open-telemetry/opentelemetry-proto/blob/9833c48ed163156e492882e35aa1a1263a1f6a01/opentelemetry/proto/metrics/v1/metrics.proto#L216

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-metadata

But there is not currently a way to generate info metrics using OTel SDKs, for example.

**Comment by bboreham** [comment]
Hello from the bug-scrub!

Should we close this as RW2 was shipped with Prometheus 3 ? @bwplotka

**Comment by bwplotka** [comment]
The RW2 is still experimental and this was a list towards stability of the protocol. Consolidated this into https://github.com/prometheus/prometheus/issues/16944, so we can close yes!
