### ISSUE TITLE
Service Discovery meta issue

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#2935]
Docs:
- [x] The API interface and the contract @fabxc 
- [x] The semantics for an SD mechanism. something like: https://prometheus.io/docs/instrumenting/writing_exporters/ ? @brian-brazil 

Others:
- [ ]  Evaluate integration testing approaches and float proposal in -dev
- [x]  Mark issues with difficulty so as to give contributors an easy way to start
- [x]  Tooling to take SD interface and have an easy way to build file_sd sidecars
- [x]  Some solid documentation of what makes in and what doesn't
- [ ]  Contact CNCF about the accounts on the several providers

In case I missed anything, please comment below and I will update the list.

/cc @juliusv @grandbora @TheTincho @cstyan @Verolop

**Comment by brian-brazil** [comment]
I was thinking more a README for both the docs.

**Comment by Gouthamve** [comment]
Yes, I don't think this should end up on the site (atleast not yet), but I
like the format for the doc. It will be a README only.

**Comment by cstyan** [comment]
do we want to discuss other issue labels now as well? re: priority/accepted feature requests

**Comment by brian-brazil** [comment]
Priority we have, it's just unused right now and Pmaybe is unaccepted requests. I believe the question was more around indicating size and suitability for new contributors.

**Comment by cstyan** [comment]
:+1: cool, just checked the labels and saw those were there. Should have checked before, but from the discussion in the SD meeting it sounded like those labels didn't already exist.

A size/easy to implement label would absolutely be nice to have :)

**Comment by juliusv** [comment]
@cstyan Yep, @Gouthamve also started a separate thread on the ML about issue labeling in general: https://groups.google.com/forum/#!topic/prometheus-developers/FdbNCX3FFRc

**Comment by brian-brazil** [comment]
#2943 has my part of the SD docs

**Comment by cstyan** [comment]
what's the status here? anything I can help with?

**Comment by krasi-georgiev** [comment]
@Gouthamve I think you can mark most of these as done or maybe even close as there are other issues covering all these I think?

**Comment by simonpasquier** [comment]
With @cstyan's work on the SD adapter and his [blog post](https://prometheus.io/blog/2018/07/05/implementing-custom-sd/) being  published, I feel too that this issue can be closed. @gouthamve?

**Comment by krasi-georgiev** [comment]
I would say good to close as well

for SD we have an issue on prombench
https://github.com/prometheus/prombench/issues/133

**Comment by rajibmitra** [comment]
@gouthamve  I would like to work on this issue as part of community bridge program if no one is actively working on it.

**Comment by bwplotka** [comment]
This issue feels quite archaic... and really done. Can we close it? (: 

![](https://media0.giphy.com/media/iVqXV4vE4DDYk/giphy.gif)

Let's create another one for any missing items plus what we want to do achieve in terms of dependencies fixes. We need to be clear about what we want to achieve, in order for contributors to help us! (((:

**Comment by brian-brazil** [comment]
Nope, not done - we still have the integration testing to do.

**Comment by bwplotka** [comment]
Can we track it in some integration issues with details?

**Comment by brian-brazil** [comment]
This issue comes from consensus at a dev summit, and the checkboxes are pretty clear.

**Comment by krajorama** [comment]
Hello from the bug scrub: this issue has stalled for 5 years. Closing due to lack of activity.
