### ISSUE TITLE
Remote Write Meta Issue

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#6333]
I'd like to collect issues around the current status of remote write so that we can better track what's still a problem, what we might want to add or improve, and dis

- [ ] 1. Revisit remote write/queue config defaults, bump samples per send/lower max shards/bump min shards.
    - [ ] add metric for remote write bandwidth
- [ ] 2. Resharding still appears to not behave correctly after restart if WAL is large.
    - [ ] add more logging around remote write's replaying of the WAL
    - [ ] come up with testing/reproduction strategy
- [ ] 3. Keep a checkpoint per remote write queue so we can attempt restart from that point in the WAL on restarts.
- [ ] 4. Documentation work; I've already started a blog post for troubleshooting remote write and turning knobs on the queue config.
- [ ] 5. Streaming remote write. 

More details: 

1. We'll want to be able to maintain the same max samples/s output with the new defaults, but bumping the max samples per send would lower the shard requirements, and upsharding can lead to DDOS like issues since we have no back pressure mechanism (related issues: https://github.com/prometheus/prometheus/issues/5166)
2. My current theory is that, if Prometheus restarts just prior to a time at which it would write a new block and truncate the WAL, the WAL is large enough that replay within remote write takes long enough that the build up of samples (since scraping has started) is enough that remote write will always be minutes behind the WAL. I believe the weight of the samples pending within the calculation isn't enough, but again this is just my theory.
3. Right now remote write starts sending samples with a timestamp after `time.Now()` when Prometheus started (more or less). On restart or config reload if remote write wasn't able to flush it's pending samples cleanly or was behind for some reason there will be samples missing in the remote storage. If remote write always starts from a checkpoint in some kind of checkpoint file for it's queue name/config hash we can avoid that situation.
4. There's still open issues that we could address via just providing better/more easily accessible documentation for remote write (related issues: https://github.com/prometheus/prometheus/issues/5709).
5. Is this something we want to do? Tom brought up that if we're going to do this we might as well just stream the WAL entirely, since the goal is to reduce network overhead this would eliminate the need to send labels with every sample. The downside to this work would be that we're putting more implementation work on the server side instead of in the client. Existing implementations may no longer work. Would this be remote write v2?

@csmarchbanks @tomwilkie @gouthamve @bboreham

**Comment by brian-brazil** [comment]
@valyala had a request around 1 iirc.

For 5, my opinion there is that's in practice going to be remote specific and thus doesn't belong in Prometheus itself as it starts to get into things like state. I've been expecting sidecars to do start consuming the WAL itself for a while now for these reasons.

**Comment by cstyan** [comment]
Yep, I liked to his issue in the details section.

For 5, what state are you referring to? Offset in the WAL that we're currently at for remote write? How is that different than if we added a timestamp/checkpoint file for the current implementation of remote write?

I think overall if we were to implement some sort of remote write streaming it's no unlikely that it would reduce the amount of code we have to maintain in Prometheus for remote write.

**Comment by brian-brazil** [comment]
> How is that different than if we added a timestamp/checkpoint file for the current implementation of remote write?

What happens if the other end needs you to restart, due to an issue on their end?

> Would this be remote write v2?

We should always have a remote write that looks like what we currently have, as that's lowest common denominator. That's the current consensus too, the protocol isn't planning on changing.

**Comment by cstyan** [comment]
> What happens if the other end needs you to restart, due to an issue on their end?

It's the same as what I'm proposing for the current implementation, we write the timestamp of the last successful sent sample (the timestamp we read from it's record in the WAL) to a file. Or the offset in the WAL.

> We should always have a remote write that looks like what we currently have, as that's lowest common denominator. That's the current consensus too, the protocol isn't planning on changing.

FWIW I'm not proposing that we make the streaming of the WAL change, just putting it up for discussion to go along with streaming RW in general, which I know has been a topic before.

**Comment by csmarchbanks** [comment]
Thank you for compiling these!

> I believe the weight of the samples pending within the calculation isn't enough, but again this is just my theory.

I don't think the behavior I see matches this theory, but maybe you see something different? If it was just about tuning the weight, then it would take a long time to catch up, but would eventually since the accumulator would still be greater than zero. The current behavior is that a non-zero equilibrium can be found, likely caused by either not accounting for all the time spent processing a sample (I know this happens, but don't know if it is a big enough deal), or a mismatch between `samplesIn` and `samplesOut`.

> 5. Streaming remote write

I was chatting some with @robskillington about it and PromCon and he sounded keen as well.

I am imagining some sort of negotiation where the server could respond saying that it needs the labels for x series. Yes, it could also be done as a sidecar (and perhaps should start as a sidecar rather than in Prometheus core), but if several remote write targets (M3, Cortex, Thanos, etc...) all want the same streaming format it might make sense to move it into core.

**Comment by cstyan** [comment]
> I don't think the behavior I see matches this theory, but maybe you see something different? If it was just about tuning the weight, then it would take a long time to catch up, but would eventually since the accumulator would still be greater than zero. The current behavior is that a non-zero equilibrium can be found, likely caused by either not accounting for all the time spent processing a sample (I know this happens, but don't know if it is a big enough deal), or a mismatch between `samplesIn` and `samplesOut`. Edit: Could also be that it wants to upshard a bit, but less than 30% and just sits there since it isn't falling further behind.

What I see is that the gap between highest timestamp in and highest timestamp sent metrics grows steadily, to the point that we've been 10+ minutes behind. With debug logging on it looks like the rates are more or less the same and resharding doesn't want to upshard. If the case is that it would eventually want to upshard, I still think the weights or part of the calculation is off. 

It's not correct for the system to take hours to recover. I don't know if it would recover, as we've never really let it go more than 30+ minutes of falling behind without clearing the WAL and restarting Prometheus again.

As I said, this is just my theory, and I want to come up with a way to reproduce the behaviour.

**Comment by csmarchbanks** [comment]
👍 falling further behind without scaling up could definitely be caused by too low of a weight and is different than the behavior of staying just a bit behind.

**Comment by cstyan** [comment]
We should discuss some base level for what's acceptable. For example, I think a being a few scrapes behind if your scrape interval is 30s is okay, but 10 minutes is definitely not.

**Comment by csmarchbanks** [comment]
Yes, I think defining a goal would be great. What about something like `batch_send_deadline` + 1m? That is assuming normal operating conditions of the backend.

**Comment by cstyan** [comment]
That sounds reasonable but we should play around with the current config and see what kind of results we can get for a given samples/second value. I'd also like to see what kind of catch-up times we see after WAL replay.

**Comment by cstyan** [comment]
Mixin improvements: #7218 https://github.com/prometheus/prometheus/issues/7176

**Comment by tangwz** [comment]
@cstyan  I would like to work this summer on this project. May I know how to start it？Can you assign me an issue?

**Comment by bwplotka** [comment]
This project is part of Community Bridge program, if you want to be mentored and help with this, please apply there :hugs: https://twitter.com/PrometheusIO/status/1258807895124303872

**Comment by cstyan** [comment]
resharding improvements #7078 https://github.com/prometheus/prometheus/issues/7230

**Comment by tangwz** [comment]
@bwplotka Thanks. I have submitted my resume and cover letter.

**Comment by cstyan** [comment]
https://github.com/prometheus/prometheus/issues/8779

**Comment by bboreham** [comment]
> the goal is to reduce network overhead this would eliminate the need to send labels with every sample

@tomwilkie mentioned this again in his Promcon talk yesterday, and it triggered me to be pedantic...

If we are concerned about _network_ overhead we should use Zstd or even Gzip instead of Snappy; I project we would see 2x-4x reduction.

However the overhead in memory allocation and management of all those repeated strings at each end is considerable, and it would be more efficient in CPU to avoid re-sending labels every time (and we could probably stop compressing so save that CPU too).

**Comment by bboreham** [comment]
Greetings from the bug-scrub, @cstyan.  We felt that [[meta] Remote write 2.0](#13105) should be linked from here.

Point 1 has been addressed, I feel, but others remain current issues and/or being worked on.

**Comment by bwplotka** [comment]
I plan to go through those this month.

**Comment by bwplotka** [comment]
Closing this after triaging all mentioned issues. There is not milestone associated to this, so we might as well track them directly on GH without meta issue.

The remote write 2.0 meta issue (new one) is here: https://github.com/prometheus/prometheus/issues/16944

The tasks from here (and other RW tasks) are available under [`component/remote storage` label](https://github.com/prometheus/prometheus/issues?q=state%3Aopen%20label%3A%22component%2Fremote%20storage%22).
